name: CordCloud

on:
  schedule:
    - cron: "1 0 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: itihub/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
          host: www.cordcloud.biz,www.cordc.xyz,www.cordc.cc,www.cordcloud.cloud,www.cordc.net
